FROM node:18.13.0 AS build

WORKDIR /app
COPY package*.json ./

RUN npm install
COPY . .

RUN npm run build
RUN npm prune --prod

FROM node:18.13.0-alpine

RUN addgroup -g 1001 appuser && adduser -u 1001 -G appuser -s /bin/sh -D appuser

WORKDIR /app

COPY --from=build /app/build ./build
COPY --from=build /app/node_modules ./build/node_modules

EXPOSE $PORT

USER appuser

ARG LOG_LEVEL=silly
ARG PROJECT_NAME=adadot-slack
ARG PORT=3100
ARG REDIS_HOST=localhost
ARG REDIS_PORT=6379
ARG ENVIRONMENT_NAME=prod
ARG SLACK_SIGNING_SECRET
ARG SLACK_APP_TOKEN
ARG ADADOT_SERVICE_TOKEN
ARG ADADOT_BACKEND_HOSTNAME

ENV LOG_LEVEL=${LOG_LEVEL}
ENV PROJECT_NAME=${PROJECT_NAME}
ENV PORT=${PORT}
ENV SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
ENV SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PORT=${REDIS_PORT}
ENV ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
ENV ADADOT_SERVICE_TOKEN=${ADADOT_SERVICE_TOKEN}
ENV ADADOT_BACKEND_HOSTNAME=${ADADOT_BACKEND_HOSTNAME}

CMD ["node", "build/index.js"]
